package com.prayer.facade.sql.special;

/**
 * 
 * @author Lang
 *
 */
public interface MsSqlStatement {
    // 存在检查语句 =======================================
    /** SQL Server检查表是否存在语句 **/
    String E_TABLE = "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE=''BASE TABLE'' AND TABLE_CATALOG = ''{0}'' AND TABLE_NAME = ''{1}''";
    /** SQL Server中检查列是否存在语句 **/
    String E_COLUMN = "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_CATALOG=''{0}'' AND TABLE_NAME=''{1}'' AND COLUMN_NAME=''{2}''";
    /** SQL Server中外键约束检查语句 **/
    String E_FK_CHECK = "SELECT COUNT(*) FROM (INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE AS CC JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC ON CC.CONSTRAINT_NAME = TC.CONSTRAINT_NAME) WHERE CC.TABLE_CATALOG=''{0}'' AND CC.TABLE_NAME=''{1}'' AND (TC.CONSTRAINT_TYPE = ''PRIMARY KEY'' OR TC.CONSTRAINT_TYPE=''UNIQUE'') AND CC.COLUMN_NAME=''{2}''";
    /** SQL Server中检查外键类型语句 **/
    String E_FK_CHECK_TYPE = "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_CATALOG=''{0}'' AND TABLE_NAME=''{1}'' AND COLUMN_NAME=''{2}'' AND DATA_TYPE=''{3}''";

    // 数据读取语句 =======================================
    /** SQL Server读取表中所有列信息 **/
    String R_COLUMNS = "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_CATALOG=''{0}'' AND TABLE_NAME=''{1}''";
    /** SQL Server中读取约束信息 **/
    String R_CONSTRAINTS = "SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_CATALOG=''{0}'' AND TABLE_NAME=''{1}'' ORDER BY CONSTRAINT_NAME";
    /** SQL Server中查询当前表的字段被引用的References列表 **/
    String R_REFERENCES = "SELECT B.CONSTRAINT_NAME,F.TABLE_NAME,F.COLUMN_NAME FROM (INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS B JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE AS F ON B.CONSTRAINT_NAME=F.CONSTRAINT_NAME JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE AS T ON T.CONSTRAINT_NAME=B.UNIQUE_CONSTRAINT_NAME) WHERE B.CONSTRAINT_CATALOG=''{0}'' AND T.TABLE_NAME=''{1}'' AND T.COLUMN_NAME=''{2}''";

    // 测试表查询 =========================================
    /** SQL Server中读取所有测试表，以TST前缀，Prayer专用 **/
    String T_TABLES = "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE=''BASE TABLE'' AND TABLE_CATALOG = ''{0}'' AND TABLE_NAME LIKE ''TST%''";
}
