---Relation Table
DROP TABLE REL_ROLE_PERM;
DROP TABLE REL_PERM_ACTION;
DROP TABLE REL_GROUP_ROLE;
DROP TABLE REL_ACCOUNT_ROLE;
DROP TABLE REL_ACCOUNT_GROUP;
DROP TABLE REL_RESOURCE_PERM;
---Entity Table
DROP TABLE SEC_ACCOUNT_MATRIX;
DROP TABLE SEC_ROLE_MATRIX;
DROP TABLE SEC_ACCOUNT;
DROP TABLE SEC_GROUP;
DROP TABLE SEC_ROLE;
DROP TABLE SEC_PERM;
DROP TABLE SEC_AUDIT;
DROP TABLE SEC_ACTION;