var value = Type.String("Email");
var name = Cond.EQ("name",value);
print(name.toSql());
var name = Cond.NEQ("name",value);
print(name.toSql());
var name = Cond.LT("name",value);
print(name.toSql());
var name = Cond.LE("name",value);
print(name.toSql());
var name = Cond.GT("name",value);
print(name.toSql());
var name = Cond.GE("name",value);
print(name.toSql());
var name = Cond.NULL("name");
print(name.toSql());
var a = Cond.NOTNULL("name");
print(a.toSql());
var b = Cond.LIKE("name",value,MatchMode.END);
print(b.toSql());
var c = Cond.AND(a,b);
print(c.toSql());
print(MatchMode.END);
print(Value.Get());
print(Value.Get(null));
print(Value.Get("Hello"));
print(Value.Updated());
print(Value.Updated(null));
print(Value.Updated("Hello"));
print(system.ID);
print($ID);